### ISSUE TITLE
Error after installing diff2html-cli

### ISSUE THREAD

**Issue by igor77ik** [rtfpessoa/diff2html#414]
### Step -1: Before filling an issue check out troubleshooting section

- Go to [README.md#Troubleshooting](https://github.com/rtfpessoa/diff2html#troubleshooting)

### Step 0: Describe your environment

- OS: CentOS 7.9
- diff2html version: last
- Using diff2html directly or using diff2html-ui helper: diff2html
- Extra flags: **\_**

### Step 1: Describe the problem:

# npm install -g diff2html-cli
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/usr/bin/diff2html -> /usr/lib/node_modules/diff2html-cli/bin/diff2html
/usr/lib
└── diff2html-cli@5.1.11 

#### Steps to reproduce:

[root@orax02]# diff2html
/usr/lib/node_modules/diff2html-cli/node_modules/clipboardy/index.js:30
exports.write = async text => {
                      ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/diff2html-cli/lib/cli.js:76:31)

**Comment by rtfpessoa** [comment]
Hello @igor77ik, that issue is regarding the cli in the [other repository](https://github.com/rtfpessoa/diff2html-cli).

Not sure I can replicate. What version of nodejs and npm are you using?

**Comment by rtfpessoa** [comment]
Closing for inactivity
